### PR TITLE
hemingway the copy

### PR DESCRIPTION
**Pull request by groovecoder**
I ran the home page copy thru hemingwayapp.com to simplify it. I think it reads nicer and gets straight to the point.

### CODE REVIEW

**Comment by groovecoder** [comment]
techlahoma_donate_hemingway

**Comment by DevinClark** [comment]
Great idea!

**Comment by amandaharlin** [comment]
:+1:

**Comment by jagthedrummer** [comment]
Looks good, thanks @groovecoder!

**Pull request merged**
